# Generated by Django 5.0.4 on 2024-04-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_controle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                ("cod_veiculo", models.AutoField(primary_key=True, serialize=False)),
                ("placa", models.CharField(max_length=7)),
                ("marca", models.CharField(max_length=20)),
                ("veiculo", models.CharField(max_length=50)),
                ("km_troca_oleo", models.IntegerField()),
            ],
        ),
    ]
