# Generated by Django 5.0.4 on 2024-04-09 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_controle", "0002_veiculo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motorista",
            name="cod_motorista",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Id"
            ),
        ),
        migrations.AlterField(
            model_name="motorista",
            name="num_cnh",
            field=models.CharField(max_length=20, verbose_name="N° da CNH"),
        ),
        migrations.AlterField(
            model_name="motorista",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="cod_veiculo",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Id"
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="km_troca_oleo",
            field=models.IntegerField(verbose_name="KM próxima troca de Óleo"),
        ),
        migrations.CreateModel(
            name="Controle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_saida", models.DateField()),
                ("hora_saida", models.TimeField()),
                ("km_saida", models.IntegerField()),
                ("destino", models.CharField(max_length=100)),
                ("data_retorno", models.DateField(blank=True, null=True)),
                ("hora_retorno", models.TimeField(blank=True, null=True)),
                ("km_retorno", models.IntegerField(blank=True, null=True)),
                ("km_percorrido", models.IntegerField(blank=True, null=True)),
                (
                    "motorista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_controle.motorista",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_controle.veiculo",
                    ),
                ),
            ],
        ),
    ]
