# Generated by Django 5.0.4 on 2024-04-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_controle", "0003_alter_motorista_cod_motorista_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controle",
            name="km_percorrido",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="controle",
            name="km_retorno",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="controle",
            name="km_saida",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
