# Generated by Django 5.0.4 on 2024-04-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_controle", "0006_alter_veiculo_placa"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="tipo_placa",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="placa",
            field=models.CharField(max_length=7),
        ),
    ]
