# Generated by Django 5.0.4 on 2024-04-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_controle", "0007_veiculo_tipo_placa_alter_veiculo_placa"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="estado",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
