# Generated by Django 5.0.4 on 2024-04-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_controle", "0009_remove_veiculo_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[("AC", "Acre"), ("AL", "Alagoas"), ("AP", "Amapá")],
                max_length=50,
                null=True,
            ),
        ),
    ]
