# Generated by Django 5.0.4 on 2024-04-12 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_controle", "0010_veiculo_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="veiculo",
            name="estado",
        ),
    ]
