# Generated by Django 5.0.4 on 2024-04-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_controle", "0011_remove_veiculo_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="controle",
            name="disponivel",
            field=models.BooleanField(default=True),
        ),
    ]
