# Generated by Django 5.0.4 on 2024-04-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_controle", "0012_controle_disponivel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controle",
            name="disponivel",
        ),
        migrations.AddField(
            model_name="veiculo",
            name="disponivel",
            field=models.BooleanField(default=True),
        ),
    ]
