# Generated by Django 5.0.4 on 2024-04-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_controle", "0013_remove_controle_disponivel_veiculo_disponivel"),
    ]

    operations = [
        migrations.AddField(
            model_name="controle",
            name="concluido",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
