# Generated by Django 5.0.4 on 2024-04-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_controle", "0014_controle_concluido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controle",
            name="concluido",
            field=models.BooleanField(default=False),
        ),
    ]
